littlelemon/frontend/urls.py
from django.urls import path, register_converter
from . import views as frontend_views
from django_ratelimit.decorators import ratelimit
from restaurant.date_converter import DateConverter
from restaurant import views as api_views


app_name="frontend"

urlpatterns = [
    path('menu-items/', frontend_views.MenuItemsTemplate.as_view(), name="menu_ui"),
    path('menu-items/<int:pk>', frontend_views.SingeItemTemplateView.as_view(), name="item_detail_ui"),
    path('book/', frontend_views.BookTableTemplate.as_view(), name="booking_ui"),

]
# NOTE: As the frontend of the application requires API calls, we make rate limits so we reduce exposure to and reducing preasure on the server.

littlelemon/littlelemon/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # Frontend where the user interacts
    path('app/',include('frontend.urls')),
    # API endpoints to call.
    path('api/', include('restaurant.urls')),
    # path('api/booking/', include(router.urls)),
    # Authentication endpoints
    path('auth/',include('djoser.urls')),
    path('auth/',include('djoser.urls.authtoken')),
]

littlelemon/restaurant/urls.py
from django.urls import path, include
from restaurant import views as api_views
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()

app_name = "restaurant"
urlpatterns = [
    path('menu/', api_views.MenuItemView.as_view()),
    path('menu/<int:pk>', api_views.SingleItemView.as_view()),
    path('', include(router.urls)),
    path('create', api_views.BookingCreate.as_view(), name="create"),
    path('bookings/<str:booking_date>', api_views.BookingCreate.as_view(), name="booking_list"),
    path('bookings/<str:booking_date>/<str:booking_slot>', api_views.BookingDetail.as_view(), name="booking_list_detail"),
    path('api-token-auth/',  obtain_auth_token),
]

 

littlelemon/restaurant/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Booking(models.Model):
    name = models.CharField(max_length=255, null=False)
    no_of_guests = models.IntegerField()
    booking_date = models.DateField();
    booking_slot = models.SmallIntegerField(default=10);

    def __str__(self):
        return f"{self.name}";

class Menu(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    inventory = models.IntegerField();

    def __str__(self):
        return f"{self.title} : {self.price}";

littlelemon/frontend/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic import TemplateView, FormView
from restaurant.views import MenuItemView
from restaurant.views import ThrottleAPIMixin, AuthenticationMixin, UserRateThrottle
from restaurant.serializers import BookingSerializer
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse


# Create your views here.

class MenuItemsTemplate(TemplateView, ThrottleAPIMixin):
    template_name = 'index.html';
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["items"] = MenuItemView.queryset.all;
        return context

class SingeItemTemplateView(TemplateView, AuthenticationMixin, UserRateThrottle):
    template_name = 'item_detail.html';
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["item"] = MenuItemView.queryset.get(pk=kwargs["pk"]);
        except:
            context[""] = ""
        return context;
 
class BookTableTemplate(TemplateView, ThrottleAPIMixin):
    template_name = 'booking.html';

littlelemon/restaurant/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from .models import Menu, Booking
from .serializers import MenuSerializer, BookingSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.throttling import AnonRateThrottle, UserRateThrottle
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from rest_framework.decorators import action;
from datetime import datetime, date
from django.shortcuts import get_object_or_404

# Create your views here.
class ThrottleAPIMixin:
    throttle_classes = [AnonRateThrottle, UserRateThrottle]

class AuthenticationMixin:
    permission_classes = [IsAuthenticated]

class MenuItemView(ListCreateAPIView, ThrottleAPIMixin):
    queryset = Menu.objects.all();
    serializer_class = MenuSerializer
    
class SingleItemView(RetrieveUpdateDestroyAPIView, ThrottleAPIMixin, AuthenticationMixin):
    queryset = Menu.objects.all();
    serializer_class = MenuSerializer
    

class BookingCreate(ListCreateAPIView):
    queryset = Booking.objects.filter(booking_date__contains=date.today());
    serializer_class = BookingSerializer

    def create(self, request, *args, **kwargs):
        form_data_json = JSONParser().parse(request);
        form_serializer = BookingSerializer(data=form_data_json);
        if form_serializer.is_valid():
            form_serializer.save();      
            return Response(form_serializer.data, status=200)
        else:
            return Response({'ERROR':f'{form_serializer.errors}'},status=403);


class BookingDetail(RetrieveUpdateDestroyAPIView):
    queryset = Booking.objects.all();
    serializer_class = BookingSerializer;
    
    def get_object(self):
        from django.core.serializers import serialize
        reservation_date = self.kwargs['booking_date']
        reservation_slot = self.kwargs['booking_slot']
        self.queryset = get_object_or_404(Booking, booking_date=reservation_date, booking_slot=reservation_slot);
        return self.queryset;

    def update(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs);

class Validate_Date(datetime):
    
    @staticmethod
    def is_valid_date(date_str):
        curr_date = datetime.today().date()
        if date_str >= str(curr_date):
            return True;
        else:
            return False;
    
    def validate_time_slot(time_slot):
        if 10 < int(time_slot) <= 20:
            return True
        else:
            return False;
       

littlelemon/templates/base.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Little Lemon</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="Based in Chicago, Illinois, Little Lemon is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist."
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
  </head>

  <body>
    <!--Header content-->
    {% include 'partials/_header.html' %}

    <main>{% block content %} {% endblock %}</main>

    <!--Footer content-->
    <!-- Replace this comment with your code  -->
        {% include 'partials/_footer.html' %}
  </body>
</html>

littlelemon/templates/booking.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section>
        <article>
        <div class="row">
            <div class="column">
            <h1>Make Reservation</h1>
               <form id="form" > 
                <p>
                <label for="first_name">Name</label>
                <input type="text" placeholder="Reservation For..." maxlength="200" id="first_name" name="first_name" required>
                </p>
                <p>
                <label for="reservation_date">Reservation Date<label>
                <input type="date" id="reservation_date" required>
                </p>
                <p>
                <div class="container">
                    <div class="column-reservation-time"> 
                        <label for="reservation_slot">Reservation time</label>
                        <select id="reservation_slot" required>
                            <option value="0" disabled>Select time</option>
                        </select>
                    </div>
                    <div class="column-guest_number">
                        <label for="guest_number">Guest No.</label>
                        <select id="guest_number" required>
                           
                        </select>
                    </div>
                    </p>
                </div>
                <button id="button">Reserve</button>
            </form>
        </div>

        <div class="column">
            <div class="videowrap">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11898.289517452584!2d-87.60853049433447!3d41.79442860243028!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2912ce6f7027%3A0xc0cfb5545d4a37b2!2sHyde%20Park%2C%20Chicago%2C%20IL%2C%20USA!5e0!3m2!1sen!2spt!4v1662384760663!5m2!1sen!2spt"
                width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>
    </article>
    </section>
    <script>
        const date = new Date()
        const month_format = date.getMonth() + 1 < 10 ? `0${date.getMonth() + 1}` : date.getMonth() + 1;
        const current_date = `${date.getFullYear()}-${month_format}-${date.getDate().toString().padStart(2, "0")}`

        const res_date = document.getElementById('reservation_date').value;
        window.addEventListener('DOMContentLoaded', (event) => {
            document.getElementById('reservation_date').value = current_date;
            get_guest_number();
            getBookings();
            
        })

        
        document.getElementById('reservation_date').addEventListener('change', getBookings);

        function getBookings(event) {
            let reserved_slots = []
            const date = document.getElementById('reservation_date').value
            const booking_check_url = get_selected_day_bookings(date);
            console.log('res date is = '+date+' and is of type '+typeof(date))

            fetch(booking_check_url)
            .then(r => r.json())
            .then(data => {
                data_json = JSON.parse(JSON.stringify(data));
                reserved_slots = []
                bookings = []

                for(let i = 0; i < data_json.length; i++){
                    reserved_slots.push(data_json[i]['booking_slot']);
                    bookings.push(`<li>${data_json[i]['name']} - ${formatTime(data_json[i]['booking_slot'])}</li>`);

                }

                slot_options = '<option value="0" disabled>Select time</option>';
                for(let i = 11; i < 23; i++){
                  const label = formatTime(i);
                  if(reserved_slots.includes(i)){
                    slot_options += `<option value=${i} disabled>${label}</option>`
        
                  }else{
                    slot_options += `<option value=${i}>${label}</option>`;
                  }
                }  
                console.log('data+ '+slot_options)
        
                document.getElementById('reservation_slot').innerHTML = slot_options
                if(bookings === ''){
                  bookings = "No bookings"
                }

            }).catch((error)=>{
                console.log("ERRPR: "+error)
            });
        }

        function formatTime(time) {
            const ampm = time < 12 ? 'AM' : 'PM'
            const t = time < 12 ? time : time > 12 ? time - 12 : time
            const label = `${t} ${ampm}`
            return label
        }

      
        document.getElementById('button').addEventListener('click', function (e) {

            const formdata = {
                "name": document.getElementById('first_name').value,
                "booking_date": document.getElementById('reservation_date').value,
                "booking_slot": document.getElementById('reservation_slot').value,
                "no_of_guests": document.getElementById('guest_number').value
                }

            console.log('form data= '+JSON.stringify(formdata));
            
            post_url = get_post_url();
            submit_data(post_url, JSON.stringify(formdata));
                
        })
       
        async function submit_data(url_directory,content){
            alert("post data is - "+url_directory)
            const csrf_token_value = Cookies.get('csrftoken');
            console.log('url data = '+url_directory);
            
            await fetch(url_directory,{
                method: 'POST',
                headers: {'X-CSRFToken' : csrf_token_value},
                body: content,
                mode: 'same-origin'
                }
            )
            .then( (response) => {
                response.clone().json();
                if(response.ok){    
                    return response.json();  
                }
                else if(response_clone.status === 429){
                    throw new Error("API POST Limit Reached - Please try again later");
                }
                else if(response_clone.status === 400){
                    throw new Error("Invalid Input - ")
                }
                else{
                    throw new Error("Unexpected Error!")
                }
            
            })
            .then(data => {                
                alert('Booking Made for '+JSON.stringify(data['name'])+' for '+JSON.stringify(data['booking_date'])+' at '+JSON.stringify(data['booking_slot'])+':00');
                document.getElementById('form').reset();
                
            }) 
            .catch((error) => {
                alert("ERROR: "+error)
            });
        };
       
        function validate_input(content){
           
        }
        
        function get_guest_number(){
            guest_number_slots = '';
            for(let i = 1; i <= 20; i++){
                if(i === 1){
                    guest_number_slots += `<option value="${i}">${i} person</option>`
                }else{
                    guest_number_slots += `<option value="${i}">${i} people</option>`
                }
            }
            document.getElementById('guest_number').innerHTML = guest_number_slots;
        }

        function get_post_url(){
            const post_url =  "{% url 'restaurant:create' %}";
            return post_url;
        }

        function get_selected_day_bookings(selected_day){
            const selected_date_url = "{% url 'restaurant:booking_list' booking_date='placeholder' %} ".replace('placeholder', selected_day);
            console.log('data ='+selected_date_url)
            return selected_date_url;
        } 
    </script>
  
    {% endblock %}

littlelemon/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <section>
         <article>
         <div class="row">
            <div class="column">  
            {% if items %}
               {% for item in items %}
               <p> <a href="{% url 'frontend:item_detail_ui' item.pk %} ">{{ item.title }}</a> <span class="menu-price"> £{{item.price}} </span> </p>
               {% endfor %}
            {% else %}
               No Menu
            {% endif %}
            </div>
         </div>
         </article>
      <section>
{% endblock %}

littlelemon/templates/item_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if item %}
        <ul>
            <li> {{ item.title }}</li>
            <li> £{{ item.price }} </li>
        </ul>
    {% else %}
        <p>Sorry - item doesn't exist on our menu</p>
    {% endif %}
{% endblock %}

littlelemon/templates/partials/_footer.html
{% load static %}
<footer>
  <article>
    <img src="{% static 'img/logo_footer.png' %}" />
  </article>
  <article>
    <p>Copyright Little Lemon</p>
  </article>
</footer>

littlelemon/templates/partials/_header.html
{% load static %}
<header>
  <img src="{% static 'img/logo.png' %}" />
</header>
<nav>
  <ul>
    
    <li><a href="{% url 'frontend:menu_ui' %}">Menu</a></li>
    <li><a href="{% url 'frontend:booking_ui' %}">Book</a></li>
   
  </ul>
</nav>